<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
		<TargetFrameworks>net6.0;net8.0</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
		<PackageReference Include="AWSSDK.SecretsManager" Version="4.0.4.20" />
		<PackageReference Include="AWSSDK.SecurityToken" Version="4.0.6.3" />
		<PackageReference Include="Keyfactor.Extensions.Aws.Auth" Version="0.5.2" />
		<PackageReference Include="Keyfactor.Logging" Version="1.3.0" />
    <PackageReference Include="Keyfactor.Orchestrators.IOrchestratorJobExtensions" Version="1.0.0" />
    <PackageReference Include="Keyfactor.PKI" Version="8.3.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Formats.Asn1" Version="10.0.8" />
  </ItemGroup>
	
	<ItemGroup>
		<None Update="manifest.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
