<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
		<TargetFrameworks>net6.0;net8.0</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<Copyright />
		<PackageLicenseExpression>https://apache.org/licenses/LICENSE-2.0</PackageLicenseExpression>
		<PackageLicenseFile></PackageLicenseFile>
		<AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<AssemblyName>Keyfactor.Extensions.Orchestrators.AWSSM</AssemblyName>
		<RootNamespace>Keyfactor.Extensions.Orchestrators.AwsSecretsManager</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
		<PackageReference Include="AWSSDK.SecretsManager" Version="4.0.0.8" />
		<PackageReference Include="AWSSDK.SecurityToken" Version="4.0.0.8" />
		<PackageReference Include="Keyfactor.Extensions.Aws.Auth" Version="0.5.1" />
		<PackageReference Include="Keyfactor.Logging" Version="1.1.2" />
    <PackageReference Include="Keyfactor.Orchestrators.IOrchestratorJobExtensions" Version="1.0.0" />
    <PackageReference Include="Keyfactor.PKI" Version="6.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Formats.Asn1" Version="9.0.6" />
  </ItemGroup>
	
	<ItemGroup>
		<None Update="manifest.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
