<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
		<TargetFrameworks>net6.0;net8.0</TargetFrameworks>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<Copyright />
		<PackageLicenseExpression>https://apache.org/licenses/LICENSE-2.0</PackageLicenseExpression>
		<PackageLicenseFile></PackageLicenseFile>
		<AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<AssemblyName>Keyfactor.Extensions.Orchestrators.AWSSM.dll</AssemblyName>
		<RootNamespace>Keyfactor.Extensions.Orchestrators.AwsSecretsManager</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
		<PackageReference Include="AWSSDK.SecretsManager" Version="3.7.400.137" />
		<PackageReference Include="AWSSDK.SecurityToken" Version="3.7.401.86" />
		<PackageReference Include="Keyfactor.Logging" Version="1.1.2" />
    <PackageReference Include="Keyfactor.Orchestrators.IOrchestratorJobExtensions" Version="0.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
  </ItemGroup>
	
	<ItemGroup>
		<None Update="manifest.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
