# Store Type creation script using kfutil
# Generated by Doctool

Write-Host "Creating store type: AWSSMPEM"
kfutil store-types create AWSSMPEM

Write-Host "Creating store type: AWSSMPFX"
kfutil store-types create AWSSMPFX

Write-Host "Creating store type: AWSSMJKS"
kfutil store-types create AWSSMJKS

