# Creates all 3 store types via the Keyfactor Command REST API
# using PowerShell Invoke-RestMethod.
#
# Authentication (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN
#
# Always required:
#   KEYFACTOR_HOSTNAME    Command hostname (e.g. my-command.example.com)
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

if (-not $env:KEYFACTOR_HOSTNAME) {
    Write-Error "KEYFACTOR_HOSTNAME is required"
    exit 1
}

$uri     = "https://$($env:KEYFACTOR_HOSTNAME)/keyfactorapi/certificatestoretypes"
$headers = @{
    'Content-Type'               = "application/json"
    'x-keyfactor-requested-with' = "APIClient"
}

# ---------------------------------------------------------------------------
# Resolve auth
# ---------------------------------------------------------------------------
if ($env:KEYFACTOR_AUTH_ACCESS_TOKEN) {
    $headers['Authorization'] = "Bearer $($env:KEYFACTOR_AUTH_ACCESS_TOKEN)"
} elseif ($env:KEYFACTOR_AUTH_CLIENT_ID -and $env:KEYFACTOR_AUTH_CLIENT_SECRET -and $env:KEYFACTOR_AUTH_TOKEN_URL) {
    Write-Host "Fetching OAuth token..."
    $tokenBody = @{
        grant_type    = 'client_credentials'
        client_id     = $env:KEYFACTOR_AUTH_CLIENT_ID
        client_secret = $env:KEYFACTOR_AUTH_CLIENT_SECRET
    }
    $tokenResp = Invoke-RestMethod -Method Post -Uri $env:KEYFACTOR_AUTH_TOKEN_URL -Body $tokenBody
    $headers['Authorization'] = "Bearer $($tokenResp.access_token)"
} elseif ($env:KEYFACTOR_USERNAME -and $env:KEYFACTOR_PASSWORD -and $env:KEYFACTOR_DOMAIN) {
    $cred = [System.Convert]::ToBase64String(
        [System.Text.Encoding]::ASCII.GetBytes(
            "$($env:KEYFACTOR_USERNAME)@$($env:KEYFACTOR_DOMAIN):$($env:KEYFACTOR_PASSWORD)"))
    $headers['Authorization'] = "Basic $cred"
} else {
    Write-Error ("Authentication required. Set one of:`n" +
        "  KEYFACTOR_AUTH_ACCESS_TOKEN`n" +
        "  KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET + KEYFACTOR_AUTH_TOKEN_URL`n" +
        "  KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN")
    exit 1
}

function New-StoreType {
    param([string]$Name, [string]$Body)
    Write-Host "Creating $Name store type..."
    try {
        Invoke-RestMethod -Method Post -Uri $uri -Headers $headers -Body $Body -ContentType "application/json" | Out-Null
        Write-Host "  OK"
    } catch {
        Write-Warning "  FAILED: $($_.Exception.Message)"
    }
}

# ---------------------------------------------------------------------------
# AWSSMPEM — AWSSMPEM
# ---------------------------------------------------------------------------
New-StoreType "AWSSMPEM" @'
{
  "Name": "AwsSecretsManager PEM",
  "ShortName": "AWSSMPEM",
  "Capability": "AWSSMPEM",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "SeparatePrivateKey",
      "DisplayName": "Store as JSON with separate private key",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "UseDefaultSdkAuth",
      "DisplayName": "Use Default SDK Auth",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "DefaultSdkAssumeRole",
      "DisplayName": "Assume new Role using Default SDK Auth",
      "Type": "Bool",
      "DependsOn": "UseDefaultSdkAuth",
      "DefaultValue": "false",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "UseOAuth",
      "DisplayName": "Use OAuth 2.0 Provider",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthScope",
      "DisplayName": "OAuth Scope",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthGrantType",
      "DisplayName": "OAuth Grant Type",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "client_credentials",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthUrl",
      "DisplayName": "OAuth Url",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "https://***/oauth2/default/v1/token",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthClientId",
      "DisplayName": "OAuth Client ID",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "OAuthClientSecret",
      "DisplayName": "OAuth Client Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "UseIAM",
      "DisplayName": "Use IAM User Auth",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "IAMUserAccessKey",
      "DisplayName": "IAM User Access Key",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "IAMUserAccessSecret",
      "DisplayName": "IAM User Access Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "ExternalId",
      "DisplayName": "sts:ExternalId",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false
    }
  ],
  "EntryParameters": [
    {
      "Name": "CertificateTags",
      "DisplayName": "Certificate Tags",
      "Description": "If desired, tags can be applied to the certificate entries in AWS Secrets Manager.  Provide them as a JSON string of key-value pairs ie: '{'tag-name': 'tag-content', 'other-tag-name': 'other-tag-content'}'",
      "Type": "string",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DefaultValue": ""
    },
    {
      "Name": "ReplicaRegions",
      "DisplayName": "Replica Regions",
      "Description": "To replicate secrets to other regions, you can provide them here as a JSON array in the format: [{ 'KmsKeyId': '<optionally specify the encryption key ID', 'Region': '<region name>'}, {...}]",
      "Type": "string",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DefaultValue": ""
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "",
  "StorePathValue": "",
  "StorePathDescription": "The store path contains the AWS region where the SecretsManager resides.  It can optionally accept values for tags OR path prefix for identifying secrets to be managed by the cert store instance.  example:'us-east-2 [prefix='dev/midwest']' or 'us-east1 [tagName='managedBy' tagValue='keyfactor']' ",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": false,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@

# ---------------------------------------------------------------------------
# AWSSMPFX — AWSSMPFX
# ---------------------------------------------------------------------------
New-StoreType "AWSSMPFX" @'
{
  "Name": "AwsSecretsManager PFX",
  "ShortName": "AWSSMPFX",
  "Capability": "AWSSMPFX",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "UseDefaultSdkAuth",
      "DisplayName": "Use Default SDK Auth",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "DefaultSdkAssumeRole",
      "DisplayName": "Assume new Role using Default SDK Auth",
      "Type": "Bool",
      "DependsOn": "UseDefaultSdkAuth",
      "DefaultValue": "false",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "UseOAuth",
      "DisplayName": "Use OAuth 2.0 Provider",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthScope",
      "DisplayName": "OAuth Scope",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthGrantType",
      "DisplayName": "OAuth Grant Type",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "client_credentials",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthUrl",
      "DisplayName": "OAuth Url",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "https://***/oauth2/default/v1/token",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthClientId",
      "DisplayName": "OAuth Client ID",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "OAuthClientSecret",
      "DisplayName": "OAuth Client Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "UseIAM",
      "DisplayName": "Use IAM User Auth",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "IAMUserAccessKey",
      "DisplayName": "IAM User Access Key",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "IAMUserAccessSecret",
      "DisplayName": "IAM User Access Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "ExternalId",
      "DisplayName": "sts:ExternalId",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false
    }
  ],
  "EntryParameters": [
    {
      "Name": "CertificateTags",
      "DisplayName": "Certificate Tags",
      "Description": "If desired, tags can be applied to the certificate entries in AWS Secrets Manager.  Provide them as a JSON string of key-value pairs ie: '{'tag-name': 'tag-content', 'other-tag-name': 'other-tag-content'}'",
      "Type": "string",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DefaultValue": ""
    },
    {
      "Name": "ReplicaRegions",
      "DisplayName": "Replica Regions",
      "Description": "To replicate secrets to other regions, you can provide them here as a JSON array in the format: [{ 'KmsKeyId': '<optionally specify the encryption key ID', 'Region': '<region name>'}, {...}]",
      "Type": "string",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DefaultValue": ""
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "",
  "StorePathValue": "",
  "StorePathDescription": "The store path contains the AWS region where the SecretsManager resides.  It can optionally accept values for tags OR path prefix for identifying secrets to be managed by the cert store instance.  example:'us-east-2 [prefix='dev/midwest']' or 'us-east1 [tagName='managedBy' tagValue='keyfactor']' ",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": false,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@

# ---------------------------------------------------------------------------
# AWSSMJKS — AWSSMJKS
# ---------------------------------------------------------------------------
New-StoreType "AWSSMJKS" @'
{
  "Name": "AwsSecretsManager JKS",
  "ShortName": "AWSSMJKS",
  "Capability": "AWSSMJKS",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "UseDefaultSdkAuth",
      "DisplayName": "Use Default SDK Auth",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "DefaultSdkAssumeRole",
      "DisplayName": "Assume new Role using Default SDK Auth",
      "Type": "Bool",
      "DependsOn": "UseDefaultSdkAuth",
      "DefaultValue": "false",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "UseOAuth",
      "DisplayName": "Use OAuth 2.0 Provider",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthScope",
      "DisplayName": "OAuth Scope",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthGrantType",
      "DisplayName": "OAuth Grant Type",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "client_credentials",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthUrl",
      "DisplayName": "OAuth Url",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "https://***/oauth2/default/v1/token",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthClientId",
      "DisplayName": "OAuth Client ID",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "OAuthClientSecret",
      "DisplayName": "OAuth Client Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "UseIAM",
      "DisplayName": "Use IAM User Auth",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "IAMUserAccessKey",
      "DisplayName": "IAM User Access Key",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "IAMUserAccessSecret",
      "DisplayName": "IAM User Access Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "ExternalId",
      "DisplayName": "sts:ExternalId",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false
    }
  ],
  "EntryParameters": [
    {
      "Name": "CertificateTags",
      "DisplayName": "Certificate Tags",
      "Description": "If desired, tags can be applied to the certificate entries in AWS Secrets Manager.  Provide them as a JSON string of key-value pairs ie: '{'tag-name': 'tag-content', 'other-tag-name': 'other-tag-content'}'",
      "Type": "string",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DefaultValue": ""
    },
    {
      "Name": "ReplicaRegions",
      "DisplayName": "Replica Regions",
      "Description": "To replicate secrets to other regions, you can provide them here as a JSON array in the format: [{ 'KmsKeyId': '<optionally specify the encryption key ID', 'Region': '<region name>'}, {...}]",
      "Type": "string",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DefaultValue": ""
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "",
  "StorePathValue": "",
  "StorePathDescription": "The store path contains the AWS region where the SecretsManager resides.  It can optionally accept values for tags OR path prefix for identifying secrets to be managed by the cert store instance.  example:'us-east-2 [prefix='dev/midwest']' or 'us-east1 [tagName='managedBy' tagValue='keyfactor']' ",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": false,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@


Write-Host "Completed."
