#!/usr/bin/env bash

# Creates all 3 store types via the Keyfactor Command REST API using curl.
#
# Authentication (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN
#
# Always required:
#   KEYFACTOR_HOSTNAME    Command hostname (e.g. my-command.example.com)
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

if [ -z "${KEYFACTOR_HOSTNAME}" ]; then
    echo "ERROR: KEYFACTOR_HOSTNAME is required"
    exit 1
fi

BASE_URL="https://${KEYFACTOR_HOSTNAME}/keyfactorapi"

# ---------------------------------------------------------------------------
# Resolve auth
# ---------------------------------------------------------------------------
if [ -n "${KEYFACTOR_AUTH_ACCESS_TOKEN}" ]; then
    BEARER_TOKEN="${KEYFACTOR_AUTH_ACCESS_TOKEN}"
elif [ -n "${KEYFACTOR_AUTH_CLIENT_ID}" ] && [ -n "${KEYFACTOR_AUTH_CLIENT_SECRET}" ] && [ -n "${KEYFACTOR_AUTH_TOKEN_URL}" ]; then
    echo "Fetching OAuth token..."
    BEARER_TOKEN=$(curl -s -X POST "${KEYFACTOR_AUTH_TOKEN_URL}" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        --data-urlencode "grant_type=client_credentials" \
        --data-urlencode "client_id=${KEYFACTOR_AUTH_CLIENT_ID}" \
        --data-urlencode "client_secret=${KEYFACTOR_AUTH_CLIENT_SECRET}" | jq -r '.access_token')
    if [ -z "${BEARER_TOKEN}" ] || [ "${BEARER_TOKEN}" = "null" ]; then
        echo "ERROR: Failed to fetch OAuth token from ${KEYFACTOR_AUTH_TOKEN_URL}"
        exit 1
    fi
elif [ -n "${KEYFACTOR_USERNAME}" ] && [ -n "${KEYFACTOR_PASSWORD}" ] && [ -n "${KEYFACTOR_DOMAIN}" ]; then
    BEARER_TOKEN=""
else
    echo "ERROR: Authentication required. Set one of:"
    echo "  KEYFACTOR_AUTH_ACCESS_TOKEN"
    echo "  KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET + KEYFACTOR_AUTH_TOKEN_URL"
    echo "  KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN"
    exit 1
fi

if [ -n "${BEARER_TOKEN}" ]; then
    CURL_AUTH=("-H" "Authorization: Bearer ${BEARER_TOKEN}")
else
    CURL_AUTH=("-u" "${KEYFACTOR_USERNAME}@${KEYFACTOR_DOMAIN}:${KEYFACTOR_PASSWORD}")
fi

create_store_type() {
    local name="$1"
    local body="$2"
    echo "Creating ${name} store type..."
    response=$(curl -s -o /dev/null -w "%{http_code}" \
        -X POST "${BASE_URL}/certificatestoretypes" \
        -H "Content-Type: application/json" \
        -H "x-keyfactor-requested-with: APIClient" \
        "${CURL_AUTH[@]}" \
        -d "${body}")
    if [ "$response" = "200" ] || [ "$response" = "201" ]; then
        echo "  OK (HTTP ${response})"
    else
        echo "  FAILED (HTTP ${response})"
    fi
}

# ---------------------------------------------------------------------------
# AWSSMPEM — AWSSMPEM
# ---------------------------------------------------------------------------
create_store_type "AWSSMPEM" '{
  "Name": "AwsSecretsManager PEM",
  "ShortName": "AWSSMPEM",
  "Capability": "AWSSMPEM",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "SeparatePrivateKey",
      "DisplayName": "Store as JSON with separate private key",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "UseDefaultSdkAuth",
      "DisplayName": "Use Default SDK Auth",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "DefaultSdkAssumeRole",
      "DisplayName": "Assume new Role using Default SDK Auth",
      "Type": "Bool",
      "DependsOn": "UseDefaultSdkAuth",
      "DefaultValue": "false",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "UseOAuth",
      "DisplayName": "Use OAuth 2.0 Provider",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthScope",
      "DisplayName": "OAuth Scope",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthGrantType",
      "DisplayName": "OAuth Grant Type",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "client_credentials",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthUrl",
      "DisplayName": "OAuth Url",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "https://***/oauth2/default/v1/token",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthClientId",
      "DisplayName": "OAuth Client ID",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "OAuthClientSecret",
      "DisplayName": "OAuth Client Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "UseIAM",
      "DisplayName": "Use IAM User Auth",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "IAMUserAccessKey",
      "DisplayName": "IAM User Access Key",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "IAMUserAccessSecret",
      "DisplayName": "IAM User Access Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "ExternalId",
      "DisplayName": "sts:ExternalId",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false
    }
  ],
  "EntryParameters": [
    {
      "Name": "CertificateTags",
      "DisplayName": "Certificate Tags",
      "Description": "If desired, tags can be applied to the certificate entries in AWS Secrets Manager.  Provide them as a JSON string of key-value pairs ie: '{'tag-name': 'tag-content', 'other-tag-name': 'other-tag-content'}'",
      "Type": "string",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DefaultValue": ""
    },
    {
      "Name": "ReplicaRegions",
      "DisplayName": "Replica Regions",
      "Description": "To replicate secrets to other regions, you can provide them here as a JSON array in the format: [{ 'KmsKeyId': '<optionally specify the encryption key ID', 'Region': '<region name>'}, {...}]",
      "Type": "string",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DefaultValue": ""
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "",
  "StorePathValue": "",
  "StorePathDescription": "The store path contains the AWS region where the SecretsManager resides.  It can optionally accept values for tags OR path prefix for identifying secrets to be managed by the cert store instance.  example:'us-east-2 [prefix='dev/midwest']' or 'us-east1 [tagName='managedBy' tagValue='keyfactor']' ",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": false,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}'

# ---------------------------------------------------------------------------
# AWSSMPFX — AWSSMPFX
# ---------------------------------------------------------------------------
create_store_type "AWSSMPFX" '{
  "Name": "AwsSecretsManager PFX",
  "ShortName": "AWSSMPFX",
  "Capability": "AWSSMPFX",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "UseDefaultSdkAuth",
      "DisplayName": "Use Default SDK Auth",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "DefaultSdkAssumeRole",
      "DisplayName": "Assume new Role using Default SDK Auth",
      "Type": "Bool",
      "DependsOn": "UseDefaultSdkAuth",
      "DefaultValue": "false",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "UseOAuth",
      "DisplayName": "Use OAuth 2.0 Provider",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthScope",
      "DisplayName": "OAuth Scope",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthGrantType",
      "DisplayName": "OAuth Grant Type",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "client_credentials",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthUrl",
      "DisplayName": "OAuth Url",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "https://***/oauth2/default/v1/token",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthClientId",
      "DisplayName": "OAuth Client ID",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "OAuthClientSecret",
      "DisplayName": "OAuth Client Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "UseIAM",
      "DisplayName": "Use IAM User Auth",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "IAMUserAccessKey",
      "DisplayName": "IAM User Access Key",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "IAMUserAccessSecret",
      "DisplayName": "IAM User Access Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "ExternalId",
      "DisplayName": "sts:ExternalId",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false
    }
  ],
  "EntryParameters": [
    {
      "Name": "CertificateTags",
      "DisplayName": "Certificate Tags",
      "Description": "If desired, tags can be applied to the certificate entries in AWS Secrets Manager.  Provide them as a JSON string of key-value pairs ie: '{'tag-name': 'tag-content', 'other-tag-name': 'other-tag-content'}'",
      "Type": "string",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DefaultValue": ""
    },
    {
      "Name": "ReplicaRegions",
      "DisplayName": "Replica Regions",
      "Description": "To replicate secrets to other regions, you can provide them here as a JSON array in the format: [{ 'KmsKeyId': '<optionally specify the encryption key ID', 'Region': '<region name>'}, {...}]",
      "Type": "string",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DefaultValue": ""
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "",
  "StorePathValue": "",
  "StorePathDescription": "The store path contains the AWS region where the SecretsManager resides.  It can optionally accept values for tags OR path prefix for identifying secrets to be managed by the cert store instance.  example:'us-east-2 [prefix='dev/midwest']' or 'us-east1 [tagName='managedBy' tagValue='keyfactor']' ",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": false,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}'

# ---------------------------------------------------------------------------
# AWSSMJKS — AWSSMJKS
# ---------------------------------------------------------------------------
create_store_type "AWSSMJKS" '{
  "Name": "AwsSecretsManager JKS",
  "ShortName": "AWSSMJKS",
  "Capability": "AWSSMJKS",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "UseDefaultSdkAuth",
      "DisplayName": "Use Default SDK Auth",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "DefaultSdkAssumeRole",
      "DisplayName": "Assume new Role using Default SDK Auth",
      "Type": "Bool",
      "DependsOn": "UseDefaultSdkAuth",
      "DefaultValue": "false",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "UseOAuth",
      "DisplayName": "Use OAuth 2.0 Provider",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthScope",
      "DisplayName": "OAuth Scope",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthGrantType",
      "DisplayName": "OAuth Grant Type",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "client_credentials",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthUrl",
      "DisplayName": "OAuth Url",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "https://***/oauth2/default/v1/token",
      "Required": false,
      "IsPAMEligible": false
    },
    {
      "Name": "OAuthClientId",
      "DisplayName": "OAuth Client ID",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "OAuthClientSecret",
      "DisplayName": "OAuth Client Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "UseIAM",
      "DisplayName": "Use IAM User Auth",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "IAMUserAccessKey",
      "DisplayName": "IAM User Access Key",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "IAMUserAccessSecret",
      "DisplayName": "IAM User Access Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true
    },
    {
      "Name": "ExternalId",
      "DisplayName": "sts:ExternalId",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false
    }
  ],
  "EntryParameters": [
    {
      "Name": "CertificateTags",
      "DisplayName": "Certificate Tags",
      "Description": "If desired, tags can be applied to the certificate entries in AWS Secrets Manager.  Provide them as a JSON string of key-value pairs ie: '{'tag-name': 'tag-content', 'other-tag-name': 'other-tag-content'}'",
      "Type": "string",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DefaultValue": ""
    },
    {
      "Name": "ReplicaRegions",
      "DisplayName": "Replica Regions",
      "Description": "To replicate secrets to other regions, you can provide them here as a JSON array in the format: [{ 'KmsKeyId': '<optionally specify the encryption key ID', 'Region': '<region name>'}, {...}]",
      "Type": "string",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DefaultValue": ""
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "",
  "StorePathValue": "",
  "StorePathDescription": "The store path contains the AWS region where the SecretsManager resides.  It can optionally accept values for tags OR path prefix for identifying secrets to be managed by the cert store instance.  example:'us-east-2 [prefix='dev/midwest']' or 'us-east1 [tagName='managedBy' tagValue='keyfactor']' ",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": false,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}'


echo "Completed."
