#!/bin/bash
# Store Type creation script using kfutil
# Generated by Doctool

set -e

echo "Creating store type: AWSSMPEM"
kfutil store-types create AWSSMPEM

echo "Creating store type: AWSSMPFX"
kfutil store-types create AWSSMPFX

echo "Creating store type: AWSSMJKS"
kfutil store-types create AWSSMJKS

